version: '3.1'

services:
  test-app:
    image: koraven/test-project:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 80:${APP_PORT:-3000}
    environment:
      PORT: ${APP_PORT:-3000}
      MONGODB_CONNSTRING: 'mongodb://appuser:apppassword@mongo/mytestdb'
  mongo:
    image: mongo:4.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mytestdb
    volumes:
      - /opt/mongo:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro