version: '3.1'

services:
  test-app:
    image: koraven/test-project:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 80:${APP_PORT:-3000}
    environment:
      PORT: ${APP_PORT:-3000}
      MONGODB_CONNSTRING: 'mongodb://mongo/mytestdb'
  mongo:
    image: mongo:4.0.13
    restart: always
    volumes:
      - /opt/mongo:/data/db