apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  containers:
  - name: test-container
    image: koraven/test-project:latest
    env:
    - name: PORT
      value: '3000'
    - name: MONGODB_CONNSTRING
      value: mongodb://test-mongo-mongodb/mytestdb
    ports:
    - containerPort: 3000